
export const GET_TODO_REQUEST="GET_TODO_REQUEST"
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS"
export const GET_TODO_FAILURE="GET_TODO_FAILURE"

export const POST_TODO_REQUEST="POST_TODO_REQUEST"
export const POST_TODO_SUCCESS="POST_TODO_SUCCESS"
export const POST_TODO_FAILURE="POST_TODO_FAILURE"

export const EDIT_TODO_REQUEST="EDIT_TODO_REQUEST"
export const EDIT_TODO_SUCCESS="EDIT_TODO_SUCCESS"
export const EDIT_TODO_FAILURE="EDIT_TODO_FAILURE"

export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE="DELETE_TODO_FAILURE"